theme: jekyll-theme-cayman

# Site Author
author:
  name             : "Jihai Dong"
  avatar           : "董济海.jpg"
  googlescholar    : "https://scholar.google.com.hk/citations?user=exVnE8S_FGcC&hl=zh-CN"
  email            :
  researchgate     :  "https://www.researchgate.net/profile/Jihai-Dong"
